# Generated by Django 3.1.7 on 2021-04-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.CharField(max_length=50),
        ),
    ]
